// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://updhpnghlyixuddxpyhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZGhwbmdobHlpeHVkZHhweWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTk5NjUsImV4cCI6MjA1Nzg3NTk2NX0.qzzGnqIwrgg07A1E1PepbxxKqmhDJ0xrp8I8LPP_MbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);